---
- name: Install winget
  hosts: winservers
  gather_facts: no

  tasks:
    - name: Create File
      win_shell: echo 'Hello, this is a sample text.' > C:\temp\test.txt
        
    - name: Check File    
      win_shell: echo C:\temp\test.txt
