---
- name: Install winget
  hosts: winservers
  gather_facts: no

  tasks:
    - name: Download winget
      win_shell: 'Hello, this is a sample text.' ! Out-File -FilePath C:\temp\
        
#    - name: Install winget    
#      win_shell:  
#        cmd: Add-AppxPackage -Path C:\temp\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
#
