---
- name: Install winget
  hosts: winservers
  gather_facts: no

  tasks:
    - name: Download winget
      win_shell: echo 'Hello, this is a sample text.' > C:\temp\test.txt
        
    - name: Install winget    
      win_shell: notepad.exe -Path C:\temp\test.txt
