- name: Install winget
  hosts: winservers
  gather_facts: no

  tasks:
    - name: Create File
      win_command: echo "Hello, this is a sample text." > C:\temp\test.txt
      register: test_output  
      
    - name: Show File  
      debug:
        var: test_output.stdout_lines