- name: setup Mysql with medium_db db and remote login
  become: yes
  hosts: databases
  tasks:
    - name: Installing Mysql and dependencies
      package:
       name: "{{item}}"
       state: present
       update_cache: yes
      loop:
       - mysql-server
       - mysql-client 
       - python3-mysqldb
       - libmysqlclient-dev
      become: yes    
    
    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes    

    - name: Secure MariaDB installation
      command: mysql_secure_installation
      args:
        creates: /etc/mysql/debian.cnf

    - name: Create a database
      mysql_db:
        name: mydatabase
        state: present

    - name: Create a database user
      mysql_user:
        name: myuser
        password: mypassword
        priv: 'mydatabase.*:ALL'
        state: present    