- name: setup Mysql
  hosts: databases
  become: yes
    tasks:
    - name: Installing Mysql and dependencies
      package:
       name: "{{item}}"
       state: present
       update_cache: yes
      loop:
       - mysql-server
       - mysql-client 
       - python3-pymysql
       - libmysqlclient-dev
      become: yes    
