---
- name: Install winget
  hosts: winservers
  gather_facts: no

  tasks:
    - name: Download winget
      win_shell:  Invoke-WebRequest -Uri "https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle" -OutFile 'C:\temp\Microsoft\'
        
#    - name: Install winget    
#      win_shell:  
#        cmd: Add-AppxPackage -Path C:\temp\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
#
