- name: Install nmap
  hosts: securitysrv
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nmap
      apt:
        name: nmap
        state: present
