---
- name: Install winget
  hosts: winservers

  tasks:
    - name: Download winget
      win_shell:
      cmd: gip 
#      win_shell:
#        cmd: Invoke-WebRequest -Uri https://aka.ms/get-winget -OutFile C:\temp\Microsoft\
        
#    - name: Install winget    
#      win_shell:  
#        cmd: Add-AppxPackage -Path C:\temp\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
#
