- name: Install nmap
  hosts: securitysrv

  become: yes
  tasks:
    - name: Install nmap
      apt:
        name: nmap
        state: present

#    - name: Ensure Nginx is running and enabled
#      service:
#        name: nginx
#        state: started
#        enabled: yes