---
- name: Install winget
  hosts: winservers
  gather_facts: no

  tasks:
    - name: Download winget
      win_shell: Invoke-WebRequest -Uri https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.7.7/npp.8.7.7.portable.x64.zip -OutFile C:\temp\
        
#    - name: Install winget    
#      win_shell:  
#        cmd: Add-AppxPackage -Path C:\temp\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
#
