---
- name: Update Ubuntu System
  hosts: webservers devservers
  become: yes
  tasks:
    - name: Print variables
      debug:
        msg: "User: {{ ansible_user }} , password: {{ ansible_password }} , becomePass: {{ansible_become_password}}"
    
    - name: Update apt cache
      apt:
        update_cache: yes
