---
- name: Update Ubuntu System
  hosts: webservers devservers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes

    - name: Reboot the system if needed
      reboot:
        when: ansible_facts['pkg_mgr'] == 'apt'