- name: Get IP configuration on Windows host
  hosts: winservers
  gather_facts: false
  tasks:
    - name: Run ipconfig
      win_command: ipconfig
      register: ipconfig_output

    - name: Display ipconfig output
      debug:
        var: ipconfig_output.stdout_lines